#!/usr/bin/with-contenv bash

s6-setuidgid nginx /etc/cont-init.d/.configuration.sh
s6-setuidgid nginx /etc/cont-init.d/.install-dependencies.sh
s6-setuidgid nginx /etc/cont-init.d/.init-application.sh
s6-setuidgid nginx /etc/cont-init.d/.db-migration.sh
s6-setuidgid nginx /etc/cont-init.d/.install-static.sh
